version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone --depth 1 https://github.com/seandkendall/genai-bedrock-chatbot.git
      - cd genai-bedrock-chatbot/cdk
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building React application..."
      - cd genai-bedrock-chatbot/cdk/react-chatbot
      - npm install
      - npm run build
      - echo "Building CDK application..."
      - cd ../
      - cdk synth
  post_build:
    commands:
      - echo "Packaging application..."
      - cd genai-bedrock-chatbot/cdk
      - mkdir -p dist
      - cp -r ./static-website-source dist/
      - cp -r ./react-chatbot/build dist/
      - cp cdk.out/ChatbotWebsiteStack.template.json dist/
artifacts:
  files:
    - '**/*'
  base-directory: genai-bedrock-chatbot/cdk/dist
