version: 0.2

phases:
  build:
    commands:
      - |
        # Define variables
        S3_KEY="DeepSeek-R1-Distill-Llama-8B/"
        
        # Check if the folder exists in the S3 bucket
        if aws s3 ls "s3://$S3_BUCKET/$S3_KEY" > /dev/null 2>&1; then
          echo "Folder $S3_KEY already exists in bucket $S3_BUCKET. Exiting successfully."
          aws codebuild stop-build --id $CODEBUILD_BUILD_ID
          exit 0
        fi

      - |
        # Proceed with the rest of the commands if the folder does not exist
        sudo dnf update -y
        sudo dnf install git-lfs -y
        git lfs install
        git clone --filter=blob:none --no-checkout https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B
        cd DeepSeek-R1-Distill-Llama-8B
        git checkout main
        git lfs pull
        cd ..
        aws s3 sync --exclude '.git*' DeepSeek-R1-Distill-Llama-8B "s3://$S3_BUCKET/$S3_KEY/"
      
      
